language: python

python:
  - "2.7"

install: "pip install -r requirements-test.txt && pip install -e ."

services:
  - memcached

script:  "python setup.py nosetests"

after_success:
    - coveralls
